# session过期
SESSION_OUTTIME = 1001
# 内部错误
INTERNAL_EXCEPTION = 1100
# 操作他人数据，越位
NO_YOU_DATA = 1101
# 权限问题
PERMISSION_ERROR = 1102
# 不正确的参数
INCORRECT_PARAM = 1103
# 不匹配规则
NO_MATCH_RULE =1105
# 接口数据错误
INTERFACE_DATA_ERROR = 1106
# 没有数据
NO_DATA = 1107
# 数据已经变动
DATA_IS_CHANGE = 1108
# 数据重复
DATA_REPEAT = 1109
# 正常数据
NORMAL_DATA = 1110
INTERFACE_CALL_ERROR = 1111

SUCCESS = 'SUCCESS'
FAILED = 'FAILED'
IsNotValid = 'IsNotValid'
AccessTimeOut = 'AccessTimeOut'
NoDataBack = 'NoDataBack'